//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineEntities : DbContext
    {
        public CineEntities()
            : base("name=CineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<CARTELERA> CARTELERA { get; set; }
        public virtual DbSet<PELICULA> PELICULA { get; set; }
        public virtual DbSet<REPORTES_DE_RESERVAS> REPORTES_DE_RESERVAS { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<SEDE> SEDE { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
