//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES_DE_RESERVAS
    {
        public int ID { get; set; }
        public System.DateTime FECHA_DE_INICIO { get; set; }
        public System.DateTime FECHA_DE_FIN { get; set; }
        public Nullable<int> ID_RESERVA { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
    }
}
