//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.REPORTES_DE_RESERVAS = new HashSet<REPORTES_DE_RESERVAS>();
        }
    
        public int ID { get; set; }
        public string VERSION { get; set; }
        public string DIA { get; set; }
        public string HORA { get; set; }
        public Nullable<int> ID_PELICULA { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
    
        public virtual PELICULA PELICULA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPORTES_DE_RESERVAS> REPORTES_DE_RESERVAS { get; set; }
        public virtual SEDE SEDE { get; set; }
    }
}
